version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --secure-file-priv=""
    environment:
      MYSQL_ROOT_PASSWORD: TomasteawitaProyecta2002!
      MYSQL_DATABASE: RestAnalytics
      MYSQL_USER: CuevaTomasArg
      MYSQL_PASSWORD: TomasteawitaProyecta2002
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      bofi_net:
        ipv4_address: 172.7.7.1
  
  django:
    build: 
      context: .
      dockerfile: Dockerfile.python
    command: tail -f /dev/null 
    working_dir: /home/app
    container_name: django-app
    volumes: 
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      bofi_net:
        ipv4_address: 172.7.7.2

networks:
  bofi_net: # Name of the network
    ipam: # IP Address Management
      driver: default
      config:
        - subnet: 172.7.7.0/16 # Subnet
        # 172.7.7.0 is the default subnet for docker
        # 16 is the number of bits used for the network