# Generated by Django 4.2.1 on 2023-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assistences',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='inassistences',
            field=models.SmallIntegerField(default=0),
        ),
    ]
