# Generated by Django 4.2.1 on 2023-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_assistences_student_inassistences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assistences',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='inassistences',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
