# Generated by Django 4.2.1 on 2023-05-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_assistences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assistences',
        ),
        migrations.RemoveField(
            model_name='student',
            name='inassistences',
        ),
    ]
